In [58]:
import numpy as np
a=np.zeros(16,dtype=int)
print(a)
a=np.ones((4,4),dtype=int)
print(a)
a=np.full((3,4),3)
print(a)
a=np.eye(4,4)
print(a)
a=np.arange(0,20,3)
print(a)
a=np.linspace(1,9,5)
print(a)
a=np.random.random([2,2])
print(a)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1][2])
print(a[:1])
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[ 9,8,7],[6,5,4],[3,2,1]]])
print(a)
b=np.copy(a)
print()
print(b)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0  3  6  9 12 15 18]
[1. 3. 5. 7. 9.]
[[0.63352188 0.83709987]
 [0.12583293 0.62509354]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[1 2 3]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]


In [33]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[ 9,8,7],[6,5,4],[3,2,1]]])
print(a)
print(a[1,-2,1])
print(a.ndim)
print("slicing a",a[:4])
print("slicing a",a[:2,1,2])
print("slicing a",a[1:,2,1])
print("slicing a",a[1:,1:,2:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
5
3
slicing a [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
slicing a [6 4]
slicing a [2]
slicing a [[[4]
  [1]]]


In [56]:
a=np.full((4,4),'siri')
b=np.eye(4,4)
print(b)
print(a)
print("length of array:",len(a))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[['siri' 'siri' 'siri' 'siri']
 ['siri' 'siri' 'siri' 'siri']
 ['siri' 'siri' 'siri' 'siri']
 ['siri' 'siri' 'siri' 'siri']]
length of array: 4


In [63]:
import array
 
s1 = array.array('i', [1, 2, 3])
s2 = array.array('i', [4, 5, 6])
 
print(s1)  
print(s2)  
s3 = s1 + s2
print(s3)  
 
s1.append(4)
print(s1)  
 
s1.insert(0, 10)
print(s1) 
 
s1.extend(s2)
print(s1) 

array('i', [1, 2, 3])
array('i', [4, 5, 6])
2
array('i', [1, 2, 3, 4, 5, 6])
array('i', [1, 2, 3, 4])
array('i', [10, 1, 2, 3, 4])
array('i', [10, 1, 2, 3, 4, 4, 5, 6])


In [55]:
a=np.full((4,4),2)
b=np.full((4,4),3)
print(a)
print(b)
c=[]
print("adiition of two matrix:")
for i in a:
    for j in b:
        c=i+j   
    print(c)
print("subraction of two matrix:")  
for i in a:
    for j in b:
        c=j-i
    print(c)    
print("multiplication of two matrix:")
for i in a: 
    for j in b:
        c=i*j
    print(c)    

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
adiition of two matrix:
[5 5 5 5]
[5 5 5 5]
[5 5 5 5]
[5 5 5 5]
subraction of two matrix:
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
multiplication of two matrix:
[6 6 6 6]
[6 6 6 6]
[6 6 6 6]
[6 6 6 6]


In [68]:
a=np.array([1,2,3,4,5,6,7,8,9])
print("minimum element in array:",a.min())
print("maximum element in array:",a.max())
print("sum of array:",a.sum())
print("mean of array:",a.mean())
print("dimention of array:",a.ndim)
print("shape of array:",a.shape)
print("standard diviation od array:",a.std())
print("size of array:",a.size)
print("bytes:-",a.nbytes)

minimum element in array: 1
maximum element in array: 9
sum of array: 45
mean of array: 5.0
dimention of array: 1
shape of array: (9,)
standard diviation od array: 2.581988897471611
size of array: 9
bytes:- 36


In [83]:
import numpy as np
a=np.arange(1,25).reshape(3,1,8)
print(a, a.ndim,a.size,a.shape)
print(a.ndim)
b=np.arange(1,25).reshape(4,2,1,3)
print(b)

[[[ 1  2  3  4  5  6  7  8]]

 [[ 9 10 11 12 13 14 15 16]]

 [[17 18 19 20 21 22 23 24]]] 3 24 (3, 1, 8)
3
[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]


 [[[13 14 15]]

  [[16 17 18]]]


 [[[19 20 21]]

  [[22 23 24]]]]
